name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install rust
        uses: hecrj/setup-rust-action@v1

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |-
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/*/.*
            src-tauri/target/*/build
            src-tauri/target/*/deps
          key:
            ${{ matrix.config.os }}-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.config.os }}-

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: npm-cache-${{ matrix.settings.target }}-${{ matrix.node }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build web
        run: yarn build

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: src-tauri

      - name: Run cargo check
        run: cargo check --locked
        working-directory: src-tauri

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        working-directory: src-tauri

      - name: Run cargo test
        run: cargo test --locked
        working-directory: src-tauri

      - name: Build App
        run: yarn tauri build

      - name: Pre-release
        run: |
          Compress-Archive -CompressionLevel Optimal -Force -Path src-tauri/target/release/chrome_password_ui.exe -DestinationPath src-tauri/target/release/chrome_password_ui-x86_64-pc-windows-msvc.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.repository, 'justjavac') &&
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            src-tauri/target/release/chrome_password_ui-x86_64-pc-windows-msvc.zip
            src-tauri/target/release/bundle/msi/chrome_password_ui_*.msi
          draft: true
